base_directory: /home/edc15/Desktop/temp
label_file: preop_gbm.label
case_id_delimiter: _
image_suffixes:
  - T1_wm
  - T2_wm
  - FLAIR_wm
  - T1gad_wm
label_suffix: tumor_seg_auto
corrected_suffix: tumor_seg_manual