base_directory: \\10.115.210.159\data\BraTS2021
label_file: preop_gbm.label
case_id_delimiter: _
image_suffixes:
  - t1
  - t2
  - flair
  - t1ce
label_suffix: seg
corrected_suffix: seg_manual