# full path to data
base_directory: \\<IP-Address>\data\meningioma\manual_correction
# relative path to label file
label_file: preop_mening.label
# the delimiter separating ID from image contrast suffix in filename
case_id_delimiter: _
# suffixes for each image contrast
image_suffixes:
  - t1_wm
  - t2_wm
  - flair_wm
  - t1c_wm
# suffix for segmentation
label_suffix: seg
# suffix for manually corrected (output) segmentation
corrected_suffix: seg-manual